version: "3"

networks:
  default:
    external: true
    name: custom-bridge

services:
  traefik:
    container_name: traefik
    image: traefik:2.6
    restart: unless-stopped
    ports:
      - 443:443/tcp
      - 22180:80/tcp
      - 22181:8080/tcp
    volumes:
      - /opt/traefik:/etc/traefik:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - TZ=${TZ}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
    labels:
      traefik.enable: true
      traefik.http.routers.api.entryPoints: https
      traefik.http.routers.api.rule: Host(`traefik.chrxnn.com`)
      traefik.http.routers.api.service: api@internal
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
      interval: 1m0s
      timeout: 10s
      retries: 3